### ISSUE TITLE
Tesla hangs while used directly and concurrently

### ISSUE THREAD

**Issue by chingan-tsc** [teamon/tesla#216]
I have a use case where I need to spawn multiple concurrent connections (by batches) and I realized sometimes Tesla just hangs indefinitely before it either 

a) start the next batch after the long wait or 
b) throw an error

```
1..500 
|> Flow.from_enumerable(stages: 100, max_demand: 1) 
|> Flow.map(fn job -> 
    {:ok, %{status: code}} = Tesla.get("some website")
    IO.inspect(code) end) 
|> Flow.run()
```

Are the some memory leak issue or am I missing something?

**Comment by chulkilee** [comment]
Could you provide more details?

- Tesla adapter in use: e.g. httpc
- Erlang version
- Elixir version
- flow version
- error message with call stack

**Comment by chingan-tsc** [comment]
Erlang/OTP 20 with Elixir 1.6.0, Flow 0.14.0. I am using Tesla directly without a client and I assume its httpc adapter. Regarding the error messages, often times its none. What I did was execute `iex -S mix` on the project directory, execute the code pasted above and most of the time it just hangs there for like 5 minutes then starts to execute the first 100 "jobs" and then it would hang again before executing the next 100 "jobs". I don't have the same problem with HTTPoison or HTTPotion (hackney and ibrowse respectively) as currently I am load testing all of them.

**Comment by chulkilee** [comment]
"Hang" may means it was waiting for connection timeout or read timeout. What is the target server?

Please use following code to see what actually is happening

```elixir
1..500
|> Flow.from_enumerable(stages: 100, max_demand: 1)
|> Flow.map(fn idx ->
  IO.puts(idx)

  case Tesla.get("http://127.0.0.1:8000") do
    {:ok, %{status: status}} -> IO.puts("#{idx} -> #{status}")
    {:error, error} -> IO.puts("#{idx} -> #{inspect(error)}")
  end
end)
|> Flow.run()
```

For example, when I test it with [python3 http.server](https://docs.python.org/3/library/http.server.html), I'm seeing `:socket_closed_remotely` error after a while.

**Comment by chulkilee** [comment]
Also note that `httpc` is pretty minimal, so it may have a little bit different behavior then other "high-level" http library. See [ERL-473](https://bugs.erlang.org/browse/ERL-473). 

Tesla may fill the gap at it's httpc adapter by retrying in certain cases by the way .

**Comment by chingan-tsc** [comment]
I am testing against this site https://en.vietnamplus.vn/health.vnp actually, but since you also have an issue with your local python3 HTTP server does it mean httpc may not be the best choice for this use case? 

Actually if you test it against a live website I think the issue is more prominent, for instance when I ran your code against a live website the number 1-100 prints instantly then it hangs, it almost seemed like httpc is having some deadlock or struggling to even initiate the first request.

**Comment by chulkilee** [comment]
I have zero problem with Elixir 1.6.6 (compiled to erlang 21) and Erlang 21.0.1 when testing  https://www.google.com/ and https://en.vietnamplus.vn/health.vnp - both return 200 for all requests.

- "1-100 prints instantly" => it spins up the first 100 parallel requests
- "it hangs" - they're still in progress

This is probably because the target server (or your network situation) does not allow opening a lot of TCP connection at once. Unlike hackney, I don't think httpc uses smart connection pooling (e.g. connection per host)

For adapter-specific option, see https://github.com/teamon/tesla/wiki/0.x-to-1.0-Migration-Guide

```elixir
MyClient.get("/", opts: [adapter: [recv_timeout: 30_000]])
```

For actual option name for `httpc`, see http://erlang.org/doc/man/httpc.html

However.. `httpc` default `timeout` (and thus `connect_timeout`) is infinity so I don't think this is a client-side problem here.

**Comment by teamon** [comment]
I don't think we can do anything more here. The issue is tagged with `httpc` for future reference.
