### ISSUE TITLE
Builder blurries  the lines between module and functions

### ISSUE THREAD

**Issue by josevalim** [teamon/tesla#220]
Currently Tesla's builder allows this syntax:

    plug fn env, _next -> env end

The problem with this approach is that the anonymous function above is not really a closure, as it is moved to inside a function. Therefore you if you attempt this:

    some_var = :ok
    plug fn env, _next -> {env, some_var} end

Compilation will ultimately fail, which breaks the semantic meaning of anonymous functions in Elixir.

The root issue is that Tesla.Builder is performing ast escaping plus code traversals, which ultimately changes the semantics of the code. It is for this reason that projects like Plug expect an atom identifying a local function, instead of allowing passing functions around:

    some_var = :ok
    plug :some_fun, some_var
    defp some_fun(env, _next, some_var), do: {env, some_var}

The macro escape+traversals introduce other issues. For example, this does not work:

    fun = fn env, _next -> {env, some_var} end
    plug fun

Nor this:

    some_module = Tesla.Middleware.MyMid
    plug some_module, some_option: :foo

My suggestion here would be to generally avoid calling prewalk, escape, and similar, as they may change the code semantics or escape a code to be evaluated later outside of its original context.

Thanks!

**Comment by teamon** [comment]
The original use case of having `fun` in place of `m` / `{m,a}` was to provide a quick adapter implementation in tests - in tesla's own tests to be fair (and "because I could" add it). I don't think it makes much sense to have it now, but I also don't know if others find it useful.

I think this is much broader topic than just "functions in macros" but the usage of macros itself.
This topic popped up recently when together with @ericmj and other we were discussing how should we build API clients libraries shared by multiple applications (what's common, what's specific, what should be configured etc).

Today, we could replace this code based on Tesla.Builder macros:

```elixir
defmodule MyClient do
  use Tesla

  plug Tesla.Middleware.BaseUrl, "https://example.com"
  plug Tesla.Middleware.JSON

  def new(token) do
    Tesla.build_client([
      {Tesla.Middleware.Headers, [{"authorization", "bearer #{token}"}]
    ])
  end

  def things(client) do
    get(client, "/things")
  end
end
```

with this one not using macros at all

```elixir
defmodule MyClient do
  @middleware [
    {Tesla.Middleware.BaseUrl, "https://example.com"},
    Tesla.Middleware.JSON
  ]
  
  def new(token) do
    Tesla.build_client([
      {Tesla.Middleware.Headers, [{"authorization", "bearer #{token}"}]
    ] ++ @middleware)
  end

  def things(client) do
    Tesla.get(client, "/things")
  end
end
```

The good thing about tesla is that the most complex part is contained in the Builder, the runtime system is based on a very simple idea of middlewares (like plug). I'm considering changing the documentation to promote macro-less style while keeping the Builder for backwards compatibility. Yet, no final decisions has been made.

**Comment by josevalim** [comment]
Right. My proposal is that the `plug` macro itself in Tesla should not do anything much different to accumulating all entries in a module attribute and then passing said list to `Tesla.build_client/1`.

In Plug, the DSL is a bit more beneficial because we can compile the list of plugs into code at compile time. But this is not possible for Tesla since your middleware is actually based on anonymous functions.

I am actually ok with the macros. You already have `build_client` and you already promote it. Although it would be nice if the macros were made as simple as possible. :)

**Comment by teamon** [comment]
Actually, the early versions of tesla were compiled to one big statement passing anonymous functions. Right now it uses a `stack :: [{m,f,a}]` that is passed as the `next` argument to middleware `call(env, next, opts)` - this allows the middleware to choose wether to call `Tesla.run` or not (i.e. cache middleware don't have to call it). I think this gives a bit more power and flexibility than plug's `:halt` special return value or `Plug.Conn.before_send` callbacks, but of course is a bit more complex because of that.

Regarding the plug macro escaping itself - I think there were some issues without it but I don't remember now, I'd need to take a look.

**Comment by teamon** [comment]
@josevalim Please take a look at [runtime middleware](https://github.com/teamon/tesla#runtime-middleware) & [`Tesla.client`](https://hexdocs.pm/tesla/Tesla.html#client/2) for macro-less usage.

**Comment by josevalim** [comment]
Beautiful, thank you so much for working on this!

**Comment by teamon** [comment]
@josevalim Do you see anything else that could be done here (regarding macros behaviour) without breaking backwards compatibility?

**Comment by josevalim** [comment]
Nope, it looks great to me as is, especially the non-macro approach!
