### ISSUE TITLE
Logger configuration is evaluated at compile time 

### ISSUE THREAD

**Issue by matijavibe** [teamon/tesla#325]
I have a question regarding the debug setting in Tesla.Middleware.Logger (version 1.3.0), currently it is set to be evaluated in compile time by using this line:

tesla/lib/tesla/middleware/logger.ex 126

`@config Application.get_env(:tesla, __MODULE__, [])`

This is ok for releases, but for local dev environment it is confusing as Tesla needs to be recompiled if for some reason you need to turn the detailed request/response in dev environment.

Is this by design, or would this also be ok:

tesla/lib/tesla/middleware/logger.ex 139
`
if Application.get_env(:tesla, __MODULE__, []) |> Keyword.get(:debug, true) do
      Logger.debug(fn -> debug(env, response, opts) end)
    end
`

If it is by design, then it would be great to update the documentation, as from the part here:
https://hexdocs.pm/tesla/Tesla.Middleware.Logger.html#module-logger-debug-output

it is not at all clear that a recompile is required if the config is introduced in dev.exs.

Also sorry for potentially bad formatting it is my first submission of an issue :)

**Comment by teamon** [comment]
This is true that the config is evaluated at compile time. I'll make sure the docs match the implementation (either compile or runtime). 

Thanks a lot and welcome to the Open Source community :)

**Comment by matijavibe** [comment]
Awesome, thanks :)

**Comment by thiamsantos** [comment]
@teamon Would be great if the configuration would be evaluated at runtime. 

In my use case I had to copy the code for logger middleware in order to be able to use the enable the logger debug via environment variables fetched used the `config/releases.exs` configuration.

I think that evaluating the configuration at runtime would make the library much more flexible. WDYT? Would you be open for a PR to change this behaviour?

**Comment by teamon** [comment]
Closed with #409
