### ISSUE TITLE
Logger and basic auth

### ISSUE THREAD

**Issue by mfeckie** [teamon/tesla#388]
Many API require the use of basic auth, but when using the Tesla Logger middleware, it leaks sensitive information in the `%Tesla.Env{}` struct.

Is there a common way to avoid this?

For example

```
error: %Tesla.Env{__client__: %Tesla.Client{adapter: {Tesla.Adapter.Gun, :call, [[timeout: 30000]]},
 fun: nil, post: [], pre: [{Tesla.Middleware.Query, :call, [[]]}, {Tesla.Middleware.BasicAuth, :call, 
[[username: "foo", password: "bar"]]}, {Tesla.Middleware.BaseUrl,
```

If there isn't a common way to do this, would you be interested in a PR to add that kind of filtering to the logger?

**Comment by chulkilee** [comment]
`Tesla.Client` holds the all information - and you shouldn't just inspect it.

I don't  think Logger prints out the all information. Does it?

If you want to always hide it, then you may implement Inspect protocol on Tesla.Client.

BTW it would be easier to change behavior by module if we use struct, not MFA, in `pre`. 

```elixir
defimpl Inspect, for: Tesla.Middleware.BasicAuth do
  def inspect(%{args: args} = val, opts) do
    val |> Map.put(:args, "<hidden>") |> Inspect.Any.inspect(opts)
  end
end
```

However, since it's MFA, you need to match the first element (middleware module) and do what you need.

**Comment by mfeckie** [comment]
Based on this line https://github.com/teamon/tesla/blob/master/lib/tesla/middleware/logger.ex#L33 , I think it does print out all of the information.

The struct that gets printed is the whole of the `Tesla.Env` which contains the sensitive data.

I am able to stop the sensitive data from leaking by implementing `Inspect` for `Tesla.Env`.

**Comment by mfeckie** [comment]
Actually digging in more, it only worked if I implement the protocol on `Tesla.Client`

**Comment by teamon** [comment]
@mfeckie Implementing `Inspect` for `Tesla.Client` or `Tesla.Env` is unfortunately global, and it would require making a decision on what to show and what to hide. If, for example, it hides `authentication` header values, it's only a partial solution since one could still leak `x-my-auth-token` header. And there are still cases where you'd like to debug those headers.

Can you show an real Tesla client example where `Logger` middleware prints the whole `Tesla.Env`?

**Comment by mfeckie** [comment]
In the end I dealt with it like this

```elixir
defimpl Inspect, for: Tesla.Client do
  @moduledoc """
  Used to prevent the basic authorization headers from leaking into the logs
  """
  def inspect(incoming, opts) do
    Map.put(incoming, :pre, "[FILTERED]")
    |> Inspect.Any.inspect(opts)
  end
end
```
