### ISSUE TITLE
DELETE should allow request body

### ISSUE THREAD

**Issue by VitorTrin** [teamon/tesla#425]
According to the [RFC](https://tools.ietf.org/html/rfc7231#section-4.3.5), DELETE may have a request body, but [Tesla.delete/3](https://hexdocs.pm/tesla/Tesla.html#delete/3) does not accept one.

**Comment by chulkilee** [comment]
You can pass `body` as option (see [Tesla.option type](https://hexdocs.pm/tesla/Tesla.html#t:option/0))

```elixir
"hello" =
  Tesla.delete!("https://httpbin.org/delete", body: "hello")
  |> Map.fetch!(:body)
  |> Jason.decode!()
  |> Map.fetch!("data")
```

Since it's not common to have request body in delete (as the RFC implies discouraging it), and there is a way to send body if needed..I think delete (helper) function not accepting body is okay.

**Comment by VitorTrin** [comment]
Then at least I propose it to be an example.

```elixir
delete!("/users")
delete!("/users", query: [scope: "admin"])
delete!(client, "/users")
delete!(client, "/users", query: [scope: "admin"])
delete!(client, "/users", body: %{id: 1})
```
